export const visaRequirements = {
  Canada: {
    Canada: [{ title: "Domestic Travel", details: "No visa required within Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Canada to Thailand." }],
  },
  France: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Canada." }],
    France: [{ title: "Domestic Travel", details: "No visa required within France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from France to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from France to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from France to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from France to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from France to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from France to Thailand." }],
  },
  Germany: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to France." }],
    Germany: [{ title: "Domestic Travel", details: "No visa required within Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Germany to Thailand." }],
  },
  UnitedStates: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Germany." }],
    UnitedStates: [{ title: "Domestic Travel", details: "No visa required within UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from UnitedStates to Thailand." }],
  },
  Brazil: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to UnitedStates." }],
    Brazil: [{ title: "Domestic Travel", details: "No visa required within Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Brazil to Thailand." }],
  },
  India: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from India to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from India to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Brazil." }],
    India: [{ title: "Domestic Travel", details: "No visa required within India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from India to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from India to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from India to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from India to Thailand." }],
  },
  Japan: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to India." }],
    Japan: [{ title: "Domestic Travel", details: "No visa required within Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Japan to Thailand." }],
  },
  Australia: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Japan." }],
    Australia: [{ title: "Domestic Travel", details: "No visa required within Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Australia to Thailand." }],
  },
  Mexico: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Australia." }],
    Mexico: [{ title: "Domestic Travel", details: "No visa required within Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Mexico to Thailand." }],
  },
  China: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from China to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from China to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from China to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Mexico." }],
    China: [{ title: "Domestic Travel", details: "No visa required within China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from China to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from China to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from China to Thailand." }],
  },
  SouthKorea: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to China." }],
    SouthKorea: [{ title: "Domestic Travel", details: "No visa required within SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthKorea to Thailand." }],
  },
  SouthAfrica: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to SouthKorea." }],
    SouthAfrica: [{ title: "Domestic Travel", details: "No visa required within SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from SouthAfrica to Thailand." }],
  },
  Argentina: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to SouthAfrica." }],
    Argentina: [{ title: "Domestic Travel", details: "No visa required within Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Argentina to Thailand." }],
  },
  Singapore: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Argentina." }],
    Singapore: [{ title: "Domestic Travel", details: "No visa required within Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Singapore to Thailand." }],
  },
  Malaysia: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Singapore." }],
    Malaysia: [{ title: "Domestic Travel", details: "No visa required within Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Malaysia to Thailand." }],
  },
  Indonesia: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Malaysia." }],
    Indonesia: [{ title: "Domestic Travel", details: "No visa required within Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Indonesia to Thailand." }],
  },
  Philippines: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Indonesia." }],
    Philippines: [{ title: "Domestic Travel", details: "No visa required within Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Philippines to Thailand." }],
  },
  Italy: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Philippines." }],
    Italy: [{ title: "Domestic Travel", details: "No visa required within Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Italy to Thailand." }],
  },
  Spain: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Italy." }],
    Spain: [{ title: "Domestic Travel", details: "No visa required within Spain." }],
    Thailand: [{ title: "Visa Policy", details: "Visa requirement for travel from Spain to Thailand." }],
  },
  Thailand: {
    Canada: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Canada." }],
    France: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to France." }],
    Germany: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Germany." }],
    UnitedStates: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to UnitedStates." }],
    Brazil: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Brazil." }],
    India: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to India." }],
    Japan: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Japan." }],
    Australia: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Australia." }],
    Mexico: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Mexico." }],
    China: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to China." }],
    SouthKorea: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to SouthKorea." }],
    SouthAfrica: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to SouthAfrica." }],
    Argentina: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Argentina." }],
    Singapore: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Singapore." }],
    Malaysia: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Malaysia." }],
    Indonesia: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Indonesia." }],
    Philippines: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Philippines." }],
    Italy: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Italy." }],
    Spain: [{ title: "Visa Policy", details: "Visa requirement for travel from Thailand to Spain." }],
    Thailand: [{ title: "Domestic Travel", details: "No visa required within Thailand." }],
  },
};
