pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r frontend/* .public
    - cp -r BookYourTrip/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master